run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - gofmt
    - ineffassign
    - staticcheck

issues:
  exclude-dirs:
    - testdata

linters-settings:
  errcheck:
    check-type-assertions: true
